feat(rollouts): Add CRUD rollouts and new evaluation operations
flipt-io/flipt-rust pull request #26
Opened 2023-07-25 17:14 UTC by yquansah

This PR does the following:
- Adds CRUD operations for new rollout endpoints for evaluation v2 feature
- Adds new evaluation operations for (variant, boolean, batch)

Completes FLI-425

2023-07-25 17:17 UTC, yquansah commented
ITs will fail until evaluation v2 feature reaches the `flipt:latest` image.

2023-07-25 18:36 UTC, markphelps requested changes
lookin good

2023-07-25 18:36 UTC, markphelps commented on src/api/evaluation.rs
> +    pub async fn boolean(&self, eval: &V2EvaluateRequest) -> Result<BooleanEvaluation> {
can we put these in their own module? that way we don't need to name the types `V2XYZ`. Its a bit confusing calling them `v2` IMO when in the API route its `/evaluate/v1`.

I think if we create a folder at `src/evaluate` then we can move all this new code there without the names coliding

2023-07-25 18:36 UTC, markphelps commented on src/api/rollout.rs
> +    pub async fn update(&self, update: &RolloutUpdateRequest) -> Result<Rollout> {
missing the `order` API impl

`pub async fn order`

2023-07-25 20:22 UTC, yquansah commented on src/api/evaluation.rs
> +    pub async fn boolean(&self, eval: &V2EvaluateRequest) -> Result<BooleanEvaluation> {
@markphelps Yeah, that makes sense so we can avoid all that prefixing. Thanks!

2023-07-25 20:22 UTC, yquansah commented on src/api/rollout.rs
> +    pub async fn update(&self, update: &RolloutUpdateRequest) -> Result<Rollout> {
@markphelps Thanks, will add that!

2023-07-26 13:36 UTC, markphelps commented on src/api/evaluation.rs
> +    pub async fn boolean(&self, eval: &V2EvaluateRequest) -> Result<BooleanEvaluation> {
I still think moving the new evaluation API to its own folder like we have for `auth` and `meta` would make the most sense, basically move the new `evaluate.rs` to `src/evaluate/mod.rs`

2023-07-27 19:51 UTC, markphelps commented on src/api/evaluation.rs
> +    pub async fn boolean(&self, eval: &V2EvaluateRequest) -> Result<BooleanEvaluation> {
@yquansah wdyt

2023-07-28 14:44 UTC, yquansah commented on src/api/evaluation.rs
> +    pub async fn boolean(&self, eval: &V2EvaluateRequest) -> Result<BooleanEvaluation> {
@markphelps Ah okay that is what you meant. Yeah I agree, since it is its own endpoint `/evaluate/v1`. That makes sense.

2023-07-31 13:18 UTC, markphelps commented
we should prob wait until `latest` gets updated today with the release of v1.24, then can ensure the ITs pass in CI

2023-07-31 15:23 UTC, markphelps requested changes

2023-07-31 15:23 UTC, markphelps commented on src/api/flag.rs
> +    pub r#type: FlagType,
i think we should make this optional so that it is backward compatible

2023-07-31 16:28 UTC, yquansah commented on src/api/flag.rs
> +    pub r#type: FlagType,
@markphelps great catch!

2023-07-31 20:02 UTC, markphelps reviewed
minor naming request, looking great though!

2023-07-31 20:02 UTC, markphelps commented on src/evaluate/mod.rs
> +pub struct EvaluateClient<'client> {
```suggestion
pub struct EvaluationClient<'client> {
```

wdyt about `%s/Evaluate/Evaluation/g` here? I think the module name can stay the same, but just for consistency maybe use `Evaluation` for all types?

2023-08-01 00:25 UTC, brettbuddin approved these changes

2023-08-01 00:41 UTC, merged